#! /bin/sh

echo $HOSTNAME | grep grendel28.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 18323 
else 
rsh grendel28.ece.ncsu.edu kill 18323 
 sleep 10 
rsh grendel28.ece.ncsu.edu kill -9 18323 
fi
