#! /bin/sh

echo $HOSTNAME | grep grendel28.ece.ncsu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 25374 
else 
rsh grendel28.ece.ncsu.edu kill 25374 
 sleep 10 
rsh grendel28.ece.ncsu.edu kill -9 25374 
fi
